In [1]:
import pandas as pd
import numpy as np

In [2]:
df_controls = pd.read_csv(r'E:\tinierZhao\US-AI-Patents-main\US-AI-Patents-main\patent_control_variable\result\control_variables.csv')

In [4]:
df_controls['patent_id'] = df_controls['patent_id'].astype('str')

In [8]:
df_controls

,patent_id,wipo_kind,num_claims,patent_year,wipo_field_id,inventor_count,ipc_class_count,num_references
0,10000000,B2,20,2018,10,1,2,2
1,10000001,B2,12,2018,29,2,3,6
2,10000002,B2,9,2018,21,4,6,3
3,10000003,B2,18,2018,29,3,7,4
4,10000004,B2,6,2018,29,2,4,2
...,...,...,...,...,...,...,...,...
7469932,9999995,B2,5,2018,29,2,3,6
7469933,9999996,B2,9,2018,23,2,3,4
7469934,9999997,B2,18,2018,26,3,3,14
7469935,9999998,B2,13,2018,29,1,4,1
7469936,9999999,B2,2,2018,29,1,1,2

In [5]:
df_energy = pd.read_csv('./data/energy_cd_1216.csv')

In [6]:
df_energy['patent_id'] = df_energy['patent_id'].astype('str')

In [11]:
df_energy = pd.merge(
    left=df_energy,
    right=df_controls[['patent_id','inventor_count','ipc_class_count','num_claims','num_references','wipo_field_id']],
    how="left" 
)

In [15]:
df_energy.dropna(inplace=True)

In [16]:
df_energy

,patent_id,base_field_id,application_year,combo_field_id,cd5_index,combo_dpe_value,inventor_count,ipc_class_count,num_claims,num_references,wipo_field_id
0,10000011,29,2017,20,0.000000,0.247378,1.0,4.0,30.0,29.0,29.0
1,10000018,29,2016,3,-0.066667,0.008914,5.0,7.0,13.0,5.0,29.0
2,10000019,29,2016,21,1.000000,0.033693,9.0,3.0,11.0,2.0,29.0
3,10000022,29,2012,17,0.428571,0.103104,2.0,4.0,21.0,1.0,29.0
4,10000023,29,2015,12,-0.008380,0.015830,2.0,4.0,20.0,30.0,29.0
...,...,...,...,...,...,...,...,...,...,...,...
1715385,9974919,23,2011,24,0.002778,0.240897,2.0,3.0,15.0,49.0,23.0
1715386,9974926,29,2015,13,-0.003226,0.018379,3.0,3.0,8.0,21.0,29.0
1715387,9974927,13,2016,29,-0.000713,0.098268,3.0,4.0,2.0,18.0,13.0
1715388,9974935,16,2013,13,0.040000,0.136749,8.0,2.0,12.0,1.0,16.0
1715389,9974936,16,2014,13,0.142857,0.173884,2.0,4.0,22.0,1.0,16.0

In [17]:
df_energy.to_csv('./data/energy_stata_1216.csv',index=False)